name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 16.8
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Build toxcalc
        run: |
          npm install
          npm run ng build
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Add 404 redirect for SPA
        run: |
          cd dist
          ln -s index.html 404.html
          cd ..
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
